name: uap_mobile1
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  google_nav_bar: ^5.0.6
  webview_flutter: ^4.2.2
  cloud_firestore: ^4.5.0
  image_picker:
  flutter:
    sdk: flutter
  # firebase_core
  firebase_core: ^2.24.2
  # firebase_auth
  firebase_auth: ^4.7.3
  get: 4.6.6

dev_dependencies:
  flutter_lints: 3.0.1
  flutter_test:
    sdk: flutter

flutter:
  fonts:
  - family: Jua
    fonts:
    - asset : assets/fonts/Jua-Regular.ttf
  uses-material-design: true
  assets:
    - assets/logo_game_mobile.png
