name: uap_mobile1
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  appwrite: ^11.0.1
  google_fonts: ^6.1.0
  google_nav_bar: ^5.0.6
  get: 4.6.6
  image_picker:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: 3.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
